name: CI/CD Workflow

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  build-and-deploy-to-pages:
    uses: ./.github/workflows/deploy.yaml
